id = "quint"
name = "Quint"
description = "Quint syntax support for zed"
version = "0.0.1"
schema_version = 1
authors = ["Masaki Nakano <admin@namachan10777.dev>"]
repository = "https://github.com/namachan1077/zed-quint"

[grammars.quint]
repository = "https://github.com/gruhn/tree-sitter-quint"
rev = "e413b1b57849a0097478548b25fcae2f3d0171d1"
