name = "Quint"
grammar = "quint"
path_suffixes = ["qnt", "quint"]
line_comments = ["// "]
block_comments = ["/* ", " */"]
autoclose_before = ")]},;"
brackets = [
  { start = "(", end = ")", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "{", end = "}", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = [
    "comment",
    "string",
  ] },
]
word_characters = ["_"]
